# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_win.ui'
#
# Created by: PyQt5 UI code generator 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1141, 837)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(5, -1, 5, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.dntDataGView = QtWidgets.QGraphicsView(self.centralwidget)
        self.dntDataGView.setObjectName("dntDataGView")
        self.gridLayout_4.addWidget(self.dntDataGView, 0, 0, 1, 3)
        self.dntGraphResetPButt = QtWidgets.QPushButton(self.centralwidget)
        self.dntGraphResetPButt.setObjectName("dntGraphResetPButt")
        self.gridLayout_4.addWidget(self.dntGraphResetPButt, 1, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 1, 0, 1, 1)
        self.dntLogRestartPButt = QtWidgets.QPushButton(self.centralwidget)
        self.dntLogRestartPButt.setObjectName("dntLogRestartPButt")
        self.gridLayout_4.addWidget(self.dntLogRestartPButt, 1, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 0, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 5, -1, 5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.mkoReconnectPButt = QtWidgets.QPushButton(self.centralwidget)
        self.mkoReconnectPButt.setObjectName("mkoReconnectPButt")
        self.horizontalLayout.addWidget(self.mkoReconnectPButt)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 4)
        self.dataGBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataGBox.sizePolicy().hasHeightForWidth())
        self.dataGBox.setSizePolicy(sizePolicy)
        self.dataGBox.setMinimumSize(QtCore.QSize(400, 0))
        self.dataGBox.setObjectName("dataGBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.dataGBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.readDataTWidget = QtWidgets.QTableWidget(self.dataGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.readDataTWidget.sizePolicy().hasHeightForWidth())
        self.readDataTWidget.setSizePolicy(sizePolicy)
        self.readDataTWidget.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.readDataTWidget.setFont(font)
        self.readDataTWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.readDataTWidget.setRowCount(50)
        self.readDataTWidget.setColumnCount(6)
        self.readDataTWidget.setObjectName("readDataTWidget")
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.readDataTWidget.setItem(0, 0, item)
        self.readDataTWidget.horizontalHeader().setDefaultSectionSize(50)
        self.readDataTWidget.horizontalHeader().setHighlightSections(False)
        self.readDataTWidget.horizontalHeader().setMinimumSectionSize(60)
        self.readDataTWidget.horizontalHeader().setStretchLastSection(True)
        self.readDataTWidget.verticalHeader().setDefaultSectionSize(30)
        self.readDataTWidget.verticalHeader().setMinimumSectionSize(25)
        self.gridLayout_3.addWidget(self.readDataTWidget, 0, 0, 1, 3)
        self.stopCyclePButt = QtWidgets.QPushButton(self.dataGBox)
        self.stopCyclePButt.setObjectName("stopCyclePButt")
        self.gridLayout_3.addWidget(self.stopCyclePButt, 4, 0, 1, 3)
        self.readDataPButt = QtWidgets.QPushButton(self.dataGBox)
        self.readDataPButt.setObjectName("readDataPButt")
        self.gridLayout_3.addWidget(self.readDataPButt, 1, 0, 1, 1)
        self.cycleReadDataSBox = QtWidgets.QSpinBox(self.dataGBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cycleReadDataSBox.sizePolicy().hasHeightForWidth())
        self.cycleReadDataSBox.setSizePolicy(sizePolicy)
        self.cycleReadDataSBox.setMinimumSize(QtCore.QSize(0, 30))
        self.cycleReadDataSBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.cycleReadDataSBox.setMinimum(1)
        self.cycleReadDataSBox.setMaximum(3600)
        self.cycleReadDataSBox.setObjectName("cycleReadDataSBox")
        self.gridLayout_3.addWidget(self.cycleReadDataSBox, 1, 2, 1, 1)
        self.cycleReadDataPButt = QtWidgets.QPushButton(self.dataGBox)
        self.cycleReadDataPButt.setMinimumSize(QtCore.QSize(170, 0))
        self.cycleReadDataPButt.setObjectName("cycleReadDataPButt")
        self.gridLayout_3.addWidget(self.cycleReadDataPButt, 1, 1, 1, 1)
        self.gridLayout.addWidget(self.dataGBox, 0, 1, 1, 1)
        self.controlGBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.controlGBox.sizePolicy().hasHeightForWidth())
        self.controlGBox.setSizePolicy(sizePolicy)
        self.controlGBox.setMinimumSize(QtCore.QSize(320, 0))
        self.controlGBox.setObjectName("controlGBox")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.controlGBox)
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 10, 0, 1, 2)
        self.getParamPButton = QtWidgets.QPushButton(self.controlGBox)
        self.getParamPButton.setObjectName("getParamPButton")
        self.gridLayout_2.addWidget(self.getParamPButton, 3, 1, 1, 1)
        self.measuremenModeLabel = QtWidgets.QLabel(self.controlGBox)
        self.measuremenModeLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.measuremenModeLabel.setObjectName("measuremenModeLabel")
        self.gridLayout_2.addWidget(self.measuremenModeLabel, 4, 0, 1, 2)
        self.oscLabel = QtWidgets.QLabel(self.controlGBox)
        self.oscLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.oscLabel.setObjectName("oscLabel")
        self.gridLayout_2.addWidget(self.oscLabel, 11, 0, 1, 2)
        self.setParamPButton = QtWidgets.QPushButton(self.controlGBox)
        self.setParamPButton.setObjectName("setParamPButton")
        self.gridLayout_2.addWidget(self.setParamPButton, 3, 0, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setContentsMargins(-1, 5, -1, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_6 = QtWidgets.QLabel(self.controlGBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout_5.addWidget(self.label_6, 0, 1, 1, 1)
        self.readOscSignKU100PButt = QtWidgets.QPushButton(self.controlGBox)
        self.readOscSignKU100PButt.setObjectName("readOscSignKU100PButt")
        self.gridLayout_5.addWidget(self.readOscSignKU100PButt, 3, 1, 1, 1)
        self.readOscSignKU1000PButt = QtWidgets.QPushButton(self.controlGBox)
        self.readOscSignKU1000PButt.setObjectName("readOscSignKU1000PButt")
        self.gridLayout_5.addWidget(self.readOscSignKU1000PButt, 4, 1, 1, 1)
        self.readOscSignKU1PButt = QtWidgets.QPushButton(self.controlGBox)
        self.readOscSignKU1PButt.setObjectName("readOscSignKU1PButt")
        self.gridLayout_5.addWidget(self.readOscSignKU1PButt, 1, 1, 1, 1)
        self.readOscZeroKU10PButt = QtWidgets.QPushButton(self.controlGBox)
        self.readOscZeroKU10PButt.setObjectName("readOscZeroKU10PButt")
        self.gridLayout_5.addWidget(self.readOscZeroKU10PButt, 2, 2, 1, 1)
        self.readOscZeroKU100PButt = QtWidgets.QPushButton(self.controlGBox)
        self.readOscZeroKU100PButt.setObjectName("readOscZeroKU100PButt")
        self.gridLayout_5.addWidget(self.readOscZeroKU100PButt, 3, 2, 1, 1)
        self.readOscSignKU10PButt = QtWidgets.QPushButton(self.controlGBox)
        self.readOscSignKU10PButt.setObjectName("readOscSignKU10PButt")
        self.gridLayout_5.addWidget(self.readOscSignKU10PButt, 2, 1, 1, 1)
        self.readOscZeroKU1PButt = QtWidgets.QPushButton(self.controlGBox)
        self.readOscZeroKU1PButt.setObjectName("readOscZeroKU1PButt")
        self.gridLayout_5.addWidget(self.readOscZeroKU1PButt, 1, 2, 1, 1)
        self.readOscZeroKU1000PButt = QtWidgets.QPushButton(self.controlGBox)
        self.readOscZeroKU1000PButt.setObjectName("readOscZeroKU1000PButt")
        self.gridLayout_5.addWidget(self.readOscZeroKU1000PButt, 4, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.controlGBox)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.gridLayout_5.addWidget(self.label, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.controlGBox)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.controlGBox)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_5.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.controlGBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.controlGBox)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_5.addWidget(self.label_4, 4, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.controlGBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout_5.addWidget(self.label_7, 0, 2, 1, 1)
        self.clearOscPButt = QtWidgets.QPushButton(self.controlGBox)
        self.clearOscPButt.setObjectName("clearOscPButt")
        self.gridLayout_5.addWidget(self.clearOscPButt, 5, 0, 1, 3)
        self.gridLayout_2.addLayout(self.gridLayout_5, 12, 0, 1, 2)
        self.cycleMeasurementPButton = QtWidgets.QPushButton(self.controlGBox)
        self.cycleMeasurementPButton.setCheckable(True)
        self.cycleMeasurementPButton.setObjectName("cycleMeasurementPButton")
        self.gridLayout_2.addWidget(self.cycleMeasurementPButton, 6, 1, 1, 1)
        self.measurementTimeSBox = QtWidgets.QSpinBox(self.controlGBox)
        self.measurementTimeSBox.setMinimum(1)
        self.measurementTimeSBox.setMaximum(20)
        self.measurementTimeSBox.setObjectName("measurementTimeSBox")
        self.gridLayout_2.addWidget(self.measurementTimeSBox, 1, 1, 1, 1)
        self.deadTimeLabel = QtWidgets.QLabel(self.controlGBox)
        self.deadTimeLabel.setObjectName("deadTimeLabel")
        self.gridLayout_2.addWidget(self.deadTimeLabel, 2, 0, 1, 1)
        self.measurementTimeLabel = QtWidgets.QLabel(self.controlGBox)
        self.measurementTimeLabel.setObjectName("measurementTimeLabel")
        self.gridLayout_2.addWidget(self.measurementTimeLabel, 1, 0, 1, 1)
        self.singleMeasurementPButton = QtWidgets.QPushButton(self.controlGBox)
        self.singleMeasurementPButton.setCheckable(True)
        self.singleMeasurementPButton.setObjectName("singleMeasurementPButton")
        self.gridLayout_2.addWidget(self.singleMeasurementPButton, 6, 0, 1, 1)
        self.deadTimeSBOX = QtWidgets.QSpinBox(self.controlGBox)
        self.deadTimeSBOX.setMinimum(20)
        self.deadTimeSBOX.setMaximum(200)
        self.deadTimeSBOX.setProperty("value", 100)
        self.deadTimeSBOX.setObjectName("deadTimeSBOX")
        self.gridLayout_2.addWidget(self.deadTimeSBOX, 2, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.controlGBox)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 0, 0, 1, 2)
        self.label_8 = QtWidgets.QLabel(self.controlGBox)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 8, 0, 1, 2)
        self.calibrationTWidget = QtWidgets.QTableWidget(self.controlGBox)
        font = QtGui.QFont()
        font.setPointSize(7)
        self.calibrationTWidget.setFont(font)
        self.calibrationTWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.calibrationTWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.calibrationTWidget.setObjectName("calibrationTWidget")
        self.calibrationTWidget.setColumnCount(2)
        self.calibrationTWidget.setRowCount(4)
        item = QtWidgets.QTableWidgetItem()
        self.calibrationTWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.calibrationTWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.calibrationTWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.calibrationTWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.calibrationTWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.calibrationTWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.calibrationTWidget.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.calibrationTWidget.setItem(0, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.calibrationTWidget.setItem(1, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.calibrationTWidget.setItem(1, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.calibrationTWidget.setItem(2, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.calibrationTWidget.setItem(2, 1, item)
        item = QtWidgets.QTableWidgetItem()
        self.calibrationTWidget.setItem(3, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.calibrationTWidget.setItem(3, 1, item)
        self.calibrationTWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.calibrationTWidget.horizontalHeader().setDefaultSectionSize(120)
        self.calibrationTWidget.horizontalHeader().setMinimumSectionSize(30)
        self.calibrationTWidget.horizontalHeader().setStretchLastSection(True)
        self.calibrationTWidget.verticalHeader().setDefaultSectionSize(30)
        self.gridLayout_2.addWidget(self.calibrationTWidget, 9, 0, 1, 2)
        self.gridLayout.addWidget(self.controlGBox, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1141, 30))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(self.menuBar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menuBar)
        self.cfgDNTConfigOpenQAction = QtWidgets.QAction(MainWindow)
        self.cfgDNTConfigOpenQAction.setObjectName("cfgDNTConfigOpenQAction")
        self.cfgDNTConfigSaveQAction = QtWidgets.QAction(MainWindow)
        self.cfgDNTConfigSaveQAction.setObjectName("cfgDNTConfigSaveQAction")
        self.action_3 = QtWidgets.QAction(MainWindow)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.cfgDNTConfigOpenQAction)
        self.menu.addAction(self.cfgDNTConfigSaveQAction)
        self.menu.addSeparator()
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ДНТ Клиент"))
        self.dntGraphResetPButt.setText(_translate("MainWindow", "Перезапуск графика"))
        self.dntLogRestartPButt.setText(_translate("MainWindow", "Перезапуск лог-файла"))
        self.mkoReconnectPButt.setText(_translate("MainWindow", "Переподключение МКО"))
        self.dataGBox.setTitle(_translate("MainWindow", "Опрос"))
        __sortingEnabled = self.readDataTWidget.isSortingEnabled()
        self.readDataTWidget.setSortingEnabled(False)
        self.readDataTWidget.setSortingEnabled(__sortingEnabled)
        self.stopCyclePButt.setText(_translate("MainWindow", "Остановить циклическое чтение"))
        self.readDataPButt.setText(_translate("MainWindow", "Чтение"))
        self.cycleReadDataPButt.setText(_translate("MainWindow", "Циклическое чтение"))
        self.controlGBox.setTitle(_translate("MainWindow", "Управление"))
        self.getParamPButton.setText(_translate("MainWindow", "Прочитать"))
        self.measuremenModeLabel.setText(_translate("MainWindow", "Режим измерение тока"))
        self.oscLabel.setText(_translate("MainWindow", "Осциллограмма"))
        self.setParamPButton.setText(_translate("MainWindow", "Установить"))
        self.label_6.setText(_translate("MainWindow", "Сигнал"))
        self.readOscSignKU100PButt.setText(_translate("MainWindow", "Чтение"))
        self.readOscSignKU1000PButt.setText(_translate("MainWindow", "Чтение"))
        self.readOscSignKU1PButt.setText(_translate("MainWindow", "Чтение"))
        self.readOscZeroKU10PButt.setText(_translate("MainWindow", "Чтение"))
        self.readOscZeroKU100PButt.setText(_translate("MainWindow", "Чтение"))
        self.readOscSignKU10PButt.setText(_translate("MainWindow", "Чтение"))
        self.readOscZeroKU1PButt.setText(_translate("MainWindow", "Чтение"))
        self.readOscZeroKU1000PButt.setText(_translate("MainWindow", "Чтение"))
        self.label.setText(_translate("MainWindow", "1"))
        self.label_3.setText(_translate("MainWindow", "100"))
        self.label_2.setText(_translate("MainWindow", "10"))
        self.label_5.setText(_translate("MainWindow", "КУ"))
        self.label_4.setText(_translate("MainWindow", "1000"))
        self.label_7.setText(_translate("MainWindow", "Ноль"))
        self.clearOscPButt.setText(_translate("MainWindow", "Очистить"))
        self.cycleMeasurementPButton.setText(_translate("MainWindow", "Циклично"))
        self.deadTimeLabel.setText(_translate("MainWindow", "Мертвое время, мс"))
        self.measurementTimeLabel.setText(_translate("MainWindow", "Время измерения, с"))
        self.singleMeasurementPButton.setText(_translate("MainWindow", "Разово"))
        self.label_10.setText(_translate("MainWindow", "Параметры измерения"))
        self.label_8.setText(_translate("MainWindow", "Калибровка"))
        item = self.calibrationTWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.calibrationTWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "10"))
        item = self.calibrationTWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "100"))
        item = self.calibrationTWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "1000"))
        item = self.calibrationTWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "A"))
        item = self.calibrationTWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "B"))
        __sortingEnabled = self.calibrationTWidget.isSortingEnabled()
        self.calibrationTWidget.setSortingEnabled(False)
        item = self.calibrationTWidget.item(0, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.calibrationTWidget.item(0, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.calibrationTWidget.item(1, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.calibrationTWidget.item(1, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.calibrationTWidget.item(2, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.calibrationTWidget.item(2, 1)
        item.setText(_translate("MainWindow", "0"))
        item = self.calibrationTWidget.item(3, 0)
        item.setText(_translate("MainWindow", "1"))
        item = self.calibrationTWidget.item(3, 1)
        item.setText(_translate("MainWindow", "0"))
        self.calibrationTWidget.setSortingEnabled(__sortingEnabled)
        self.menu.setTitle(_translate("MainWindow", "Файл"))
        self.cfgDNTConfigOpenQAction.setText(_translate("MainWindow", "Открыть"))
        self.cfgDNTConfigSaveQAction.setText(_translate("MainWindow", "Сохранить"))
        self.action_3.setText(_translate("MainWindow", "ДНТ по умолчанию"))


